name: Publish
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
        env:
          NPM_TOKEN: ${{ secrets.BUILDER_TOKEN }}
      - run: npm run build
      - run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.BUILDER_TOKEN }}
